### ISSUE TITLE
Question about reference aggregation

### ISSUE THREAD

**Issue by de9uch1** [jvamvas/fastChrF#1]
Hi, thank you for releasing this package.

I have a question about reference aggregation.

https://github.com/jvamvas/fastChrF/blob/b59c9274014f47c938710082061209bb56b06520/src/lib.rs#L227
In this line, n-grams of a hypothesis are multiplied by `num_references`, instead of dividing n-grams for all references by `num_references` (multiplying 1/m) like Equation (6) in the paper https://arxiv.org/pdf/2402.04251.
I understood that this is because the final result is probably the same, and also by not dividing, there is no need to convert the type from `u32` to `f32`, making it easier to utilize the existing function `get_match_statistics`, is this correct?

**Comment by jvamvas** [comment]
Hi @de9uch1, thanks for having a look at the code! :)

Yes, you are right, this is a micro-optimization to avoid having to cast to `f32`. Mathematically, it's equivalent, so the final result should be exactly the same.

**Comment by de9uch1** [comment]
It makes sense.
Thank you so much for your quick reply.
